# Generated by Django 2.2.4 on 2019-08-21 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, max_length=200, null=True)),
                ('user_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MAIN_APP.User')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread', models.CharField(max_length=100)),
                ('board', models.CharField(max_length=100)),
                ('op_post', models.TextField()),
                ('thread_date', models.DateTimeField(auto_now=True)),
                ('thread_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MAIN_APP.User')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField()),
                ('login', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('thread', models.ManyToManyField(to='MAIN_APP.Thread')),
            ],
        ),
    ]
