# Generated by Django 2.2.4 on 2019-08-23 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN_APP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thread',
        ),
        migrations.AddField(
            model_name='post',
            name='thread',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='MAIN_APP.Thread'),
            preserve_default=False,
        ),
    ]
