# Generated by Django 2.2.4 on 2019-08-26 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN_APP', '0003_auto_20190826_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='login',
            new_name='username',
        ),
    ]
