# Generated by Django 2.2.4 on 2019-08-26 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN_APP', '0004_auto_20190826_1607'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_info',
        ),
    ]
