# Generated by Django 2.2.4 on 2019-08-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN_APP', '0006_user_det'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_det',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
