# Generated by Django 2.2.4 on 2019-08-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN_APP', '0008_auto_20190829_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/forthreads'),
        ),
    ]
