# Generated by Django 2.2.4 on 2019-08-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN_APP', '0009_auto_20190830_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='threads'),
        ),
    ]
