# Generated by Django 2.2.4 on 2019-09-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN_APP', '0010_auto_20190830_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='posts'),
        ),
    ]
