# Generated by Django 2.2.4 on 2019-09-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN_APP', '0011_auto_20190901_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='posts'),
        ),
    ]
