# Generated by Django 2.2.4 on 2019-09-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN_APP', '0014_auto_20190901_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_det',
            name='pic',
            field=models.ImageField(default=None, upload_to='users'),
        ),
    ]
